# Generated by Django 3.0.8 on 2020-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=50)),
                ('files', models.ImageField(upload_to='files')),
                ('rollno', models.CharField(max_length=100)),
            ],
        ),
    ]
