# Generated by Django 3.0.5 on 2020-07-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploads',
            table='student_uploads',
        ),
    ]
