# Generated by Django 3.0.5 on 2020-07-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200710_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='files',
            field=models.ImageField(upload_to='media/files'),
        ),
    ]
